SELECT U.USER_ID as USER_ID, U.NICKNAME as NICKNAME, sum(B.price) as TOTAL_SALES
from USED_GOODS_BOARD B join USED_GOODS_USER U on B.WRITER_ID = U.USER_ID
WHERE STATUS = 'DONE'
group by NICKNAME
HAVING TOTAL_SALES >= 700000
order by TOTAL_SALES;

